### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by adtrevor** [swift-server/swift-nio-http-client#21]
Hello and thank you for this package!
I have some ideas for improvement and would appreciate to get feedback on those! 🙂

# Performance
## Pooling
Users who make a large number of concurrent requests would strongly benefit from having a pool from which the HTTP client would pick tasks in order to optimise them.

## Fallback to multiple concurrent connections on HTTP/1.1
When HTTP/2 multiplexing isn't available, the client could open multiple HTTP/1.1 connections to a same server just like what web browsers do.

## DNS caching
SwiftNIO already lets users provide their own DNS resolver, which also allows implementing a local DNS cache. The client could let users to specify their own resolver, and why not provide a higher-level mechanism that would still take care of the actual resolving as the default resolver does, but ask the user to inject their persistence mechanism.

# Redirection improvements
Currently, the client doesn't detect redirect cycles. [The HTTP/1.1 standard, section 10.3](https://tools.ietf.org/html/rfc2616#section-10.3) specifies that:
> A client SHOULD detect infinite redirection loops, since such loops generate network traffic for each redirection.

Enabling additional redirection options would also be interesting, for instance:
- Specifying a max redirection count
- Allowing to choose between different redirection policies, for example:
```swift
public enum Policy {
                /// Refuse all redirections
                case refuseAll
                
                /// Accepts scheme replacement from `http` to `https`
                /// but only if URI stays the same
                case acceptSameURISecurityUpgrade
                
                /// Accept strictly the same domain
                case acceptSameDomain
                
                /// Accept also subdomains
                case acceptSameDomainAndSubdomains
                
                /// Accept any domain
                case acceptAll
                
                /// Choose manually
                case custom(handler: (URL)->EventLoopFuture<Bool>)
            }
```
- If it ever makes sense for some users to access the content of the redirect pages, maybe provide a mechanism for this?

# Configuration options
## Request specific options
Just as timeout and redirect options can already be set per request, I hope all configuration options can be specified per request as long as it makes sense.

## Output traffic to `.pcap` files
Use what's been done in https://github.com/apple/swift-nio-extras/pull/46 to allow debug inspection of TLS traffic with tools such as `Wireshark` or `tcpdump`.
(Thanks @tanner0101 for showing me this)

## Allow users to inject their custom behaviour / NIO handlers
If possible, this would provide greater customisation options without making the client overly complex for rarely used features.

**Comment by Lukasa** [comment]
The fallback to concurrent connections idea should be part of a wider pooling discussion. The correct abstraction for a connection pool from the perspective of the rest of the code is "ask for a connection, get back a future that fulfils with one". How that future is fulfilled is an implementation strategy of the pool. In general, the pool should do N-ary connnections except for protocols that explicitly require multiplexing (e.g. HTTP/2).

Re DNS caching, I'm highly suspicious of solving this separately from the resolver. The resolver should own caching.

Rather than support outputting traffic to PCAP files, it would likely be better to provide an escape hatch for pipeline configuration that would allow users to add PCAP handlers themselves, as you've suggested separately.

**Comment by artemredkin** [comment]
Thank you for feedback!

Regarding custom redirects, what do you think about API similar to `URLSession`:
```swift
protocol HTTPDelegate {
    func willRedirect(to url: URL) -> Bool
}
```

**Comment by adtrevor** [comment]
@Lukasa Thanks again for your feedback. As discussed I'll soon open an issue to get pool design ideas so that anyone who wants can use it as a starting point for an implementation. I'll give it a go and see where this leads me.

@artemredkin Thank you! The points I'm thinking about are:
- Should we consider some redirection policies as needed commonly enough to be implemented by the client itself?
- Regarding the potential need to download the content of a redirect response: there probably are cases where this would be wanted, if there is a redirection delegate maybe it could also get to choose wether or not it wants to read it's contents?
- Should we use a delegate or a closure?

**Comment by weissi** [comment]
Just in case someone wanted to work on the pcap stuff, I happened to have a WIP patch lying around anyway: [pcaps.txt](https://github.com/swift-server/swift-nio-http-client/files/3127265/pcaps.txt)

If you save the `pcaps.txt` as `pcaps.patch` (sorry, github doesn't allow `.patch` extensions!?!) you should be able to `git apply pcaps.patch`.

**Comment by adtrevor** [comment]
@weissi Thank you!

Will close this issue for now since I opened a new issue regarding pooling design advice (#25 ).
