### ISSUE TITLE
HTTPCookie conflicts with Foundation

### ISSUE THREAD

**Issue by adtrevor** [swift-server/swift-nio-http-client#32]
The `HTTPCookie` type conflicts with the one from `Foundation`:
```swift
import NIOHTTPClient
import Foundation
let cookie: HTTPCookie // Error: 'HTTPCookie' is ambiguous for type lookup in this context
```

Maybe it should be made  a subtype of `HTTPClient`, to have something such as `HTTPClient.Cookie`?

**Comment by jrtibbetts** [comment]
You can qualify it with the package name to avoid ambiguity, e.g. `NIOHTTPClient.HTTPCookie`.

**Comment by weissi** [comment]
@jrtibbetts Yes, you can quality but I still think it's a good goal to at least not conflict with the basic libraries. Why? Let's assume you write code that doesn't `import Foundation` so you just use `HTTPCookie` everywhere. Further down the line you might want to add `import Foundation` and suddenly you need to qualify all uses of `HTTPCookie` which isn't too hard but not great.

So I'd say from a developer ergonomics point of view, we should aim to not clash with at least the stdlib, Foundation, and NIO.

**Comment by jrtibbetts** [comment]
Oh, I completely agree that it should be renamed; I was just suggesting a workaround in the meantime.

**Comment by weissi** [comment]
> Oh, I completely agree that it should be renamed; I was just suggesting a workaround in the meantime.

Ah sorry, misunderstood you!

**Comment by Yasumoto** [comment]
Bumped into this myself so figured I'd pitch in with a take in #36.
