### ISSUE TITLE
Channel doesn't close on TaskCancelEvent/IdleStateEvent

### ISSUE THREAD

**Issue by adtrevor** [swift-server/swift-nio-http-client#33]
Currently, the `TaskHandler` doesn't close the channel when it receives an `IdleStateHandler.IdleStateEvent` or a `TaskCancelEvent`.
This is something I'll probably fix in #31 because the way those events are handled will depend on wether or not a connection is currently leased.

**Comment by artemredkin** [comment]
This should be fixed now (@adtrevor)

**Comment by adtrevor** [comment]
Thank you!
