### ISSUE TITLE
Take Retry-After value into account on 3xx responses

### ISSUE THREAD

**Issue by adtrevor** [swift-server/swift-nio-http-client#39]
A server might specify a minimum amount of time to wait before redirection using the `Retry-After` header, it should probably be taken into account by the client.

**Comment by adtrevor** [comment]
In my tests, I just noticed that although the specs specifies this usage, no browser seems to take `Retry-After` into account on 3xx.

**Comment by Lukasa** [comment]
Yeah, `Retry-After` on 3xx is not really a thing: I wouldn't bother.

**Comment by adtrevor** [comment]
Thanks, closing this then.
